# Faire un build du site et valider tous les HTML/CSS

name: Build and valid HTML/CSS

on:
  push:
    branches:
      - 'website/**'
      - 'CI/**'
  pull_request:
    branches:
      - 'website/**'
      - 'CI/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Sass
        run: npm install -g sass

      - name: Get wsbuilder
        run: |
          curl -fo wsbuilder https://raw.githubusercontent.com/Alexandre-SBEGHEN/Website-Builder/main/wsbuilder
          chmod +x wsbuilder

      - name: Build website
        run: ./wsbuilder --sass-compile --sass-compress --sass-no-source-map --css-minify --js-minify website/

      - name: Validate CSS
        run: |
          npm install -g w3c-css-validator
          for f in $(find website/*); do
              extension="${f##*.}"
              [[ "$extension" = "css" ]] && css-validator "$f"
          done
